//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FOOP202Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int TypeTypeId { get; set; }
        public string Source { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
